baseURL = "http://xai.today/"
languageCode = "en-gb"
title = "XAI Today"
theme = "minimal"
disqusShortname = "julianhatwell" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Julian Hatwell"
    description = "Commentaries on Machine Learning, Data Mining and Analytics."
    githubUsername = "julianhatwell"
    accent = "#FFAA00"
    showBorder = true
    backgroundColor = "white"
    font = "Ubuntu" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["r", "python", "scala"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2
    
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:julian@xai.today"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/julianhatwell/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/julianhatwell/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/julian-hatwell-2297855/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/julianhatwell/"
    name = "instagram"
    weight = 5
