baseURL = "https://xai.today/"
languageCode = "en-us"
title = "XAI Today"
theme = "ezhil"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
disqusShortname = "julianhatwell"

summaryLength = 20

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	subtitle = "Machine Learning, Data Mining and Analytics"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Taest"
url = "/taest"
weight = 5

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:julian@xai.today"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/julianhatwell/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/julian-hatwell-2297855/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/julianhatwell"

[taxonomies]
   tag = "tags"
